# Generated by Django 3.1.5 on 2021-01-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200625_0504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
