# Generated by Django 3.0 on 2020-07-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='Post',
        ),
    ]
