# Generated by Django 3.0 on 2020-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='itemOwner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='itemOwnerContact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
